name: driver_dispatch_app
description: "Driver Dispatch Application"
publish_to: 'none'

version: 1.0.0+17

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # ğŸŒ Needed for French Date Picker
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ğŸ”¥ Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1

  # â° French Date + Time formatting â€” MUST MATCH SDK
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
